"""add_pt_locker_service_pricing_tables

Revision ID: 2a6f2bc72640
Revises: 65ce71ce74ad
Create Date: 2026-07-09 13:33:59.348513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a6f2bc72640'
down_revision: Union[str, Sequence[str], None] = '65ce71ce74ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_services',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Name of the service (e.g. Body Massage, Premium Massage)'),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Price of the service in INR'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of the service'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Flag indicating if the service is active and purchaseable'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_additional_services')),
    sa.UniqueConstraint('name', name=op.f('uq_additional_services_name')),
    comment='Stores optional additional services configurations and pricing'
    )
    with op.batch_alter_table('additional_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_additional_services_id'), ['id'], unique=False)

    op.create_table('locker_plans',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Locker plan descriptor (e.g. Standard Locker)'),
    sa.Column('deposit', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Security deposit fee'),
    sa.Column('monthly_rent', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Locker rental fee per month'),
    sa.Column('quarterly_rent', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Locker rental fee per quarter (3 months)'),
    sa.Column('late_fee', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Late return penalty fee'),
    sa.Column('refundable', sa.Boolean(), nullable=False, comment='Flag indicating if the deposit is refundable'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Flag indicating if this locker configuration is active'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locker_plans')),
    sa.UniqueConstraint('name', name=op.f('uq_locker_plans_name')),
    comment='Stores gym locker rental configurations and deposits'
    )
    with op.batch_alter_table('locker_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locker_plans_id'), ['id'], unique=False)

    op.create_table('pt_plans',
    sa.Column('package_name', sa.String(length=255), nullable=False, comment='Name of the package (e.g. Silver, Gold, Platinum)'),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Monthly price of the PT package in INR'),
    sa.Column('session_count', sa.Integer(), nullable=False, comment='Number of coaching sessions included in this package'),
    sa.Column('whatsapp_support', sa.Boolean(), nullable=False, comment='Flag indicating if WhatsApp support is included'),
    sa.Column('locker_included', sa.Boolean(), nullable=False, comment='Flag indicating if locker facility is included'),
    sa.Column('transformation_included', sa.Boolean(), nullable=False, comment='Flag indicating if transformation guidance is included'),
    sa.Column('diet_included', sa.Boolean(), nullable=False, comment='Flag indicating if diet plans are included'),
    sa.Column('stretching_included', sa.Boolean(), nullable=False, comment='Flag indicating if stretching sessions are included'),
    sa.Column('supplement_guidance', sa.Boolean(), nullable=False, comment='Flag indicating if supplement guidance is included'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of the package'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Flag indicating if package is active and purchaseable'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pt_plans')),
    sa.UniqueConstraint('package_name', name=op.f('uq_pt_plans_package_name')),
    comment='Stores personal trainer subscription packages and features'
    )
    with op.batch_alter_table('pt_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pt_plans_id'), ['id'], unique=False)

    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True, comment='Category grouping for this membership plan'))
        batch_op.add_column(sa.Column('admission_fee', sa.DECIMAL(precision=10, scale=2), nullable=False, server_default='0', comment='Admission fee for new memberships under this plan'))
        batch_op.add_column(sa.Column('tax', sa.DECIMAL(precision=5, scale=2), nullable=False, server_default='0', comment='Applicable tax/GST percentage'))
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=True, comment='Display color theme for this plan card in frontend'))

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_details', sa.JSON(), nullable=True, comment='JSON snapshot of detailed itemized billing calculations'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_details', sa.JSON(), nullable=True, comment='JSON snapshot of detailed itemized invoice breakdown'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('billing_details')

    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_column('billing_details')

    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('tax')
        batch_op.drop_column('admission_fee')
        batch_op.drop_column('category')

    with op.batch_alter_table('pt_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pt_plans_id'))

    op.drop_table('pt_plans')
    with op.batch_alter_table('locker_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locker_plans_id'))

    op.drop_table('locker_plans')
    with op.batch_alter_table('additional_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_additional_services_id'))

    op.drop_table('additional_services')
    # ### end Alembic commands ###
