"""add_salary_shift_to_profiles

Revision ID: 4173fc7fe402
Revises: 432277b6125a
Create Date: 2026-07-05 13:32:04.469998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4173fc7fe402'
down_revision: Union[str, Sequence[str], None] = '432277b6125a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='Full name of the prospective member'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='Contact phone number'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Email address of the lead'),
    sa.Column('age', sa.Integer(), nullable=True, comment='Age of the lead'),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='lead_gender'), nullable=True, comment='Gender classification'),
    sa.Column('interest', sa.String(length=255), nullable=True, comment='Primary fitness interest (e.g. Weight Loss, Muscle Gain)'),
    sa.Column('source', sa.Enum('WALK_IN', 'REFERRAL', 'SOCIAL_MEDIA', 'PHONE', 'OTHER', name='leadsource'), nullable=False, comment='Lead acquisition source'),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'TRIAL', 'CONVERTED', 'LOST', name='leadstatus'), nullable=False, comment='Lead conversion status pipeline state'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Follow up and inquiry logs'),
    sa.Column('follow_up_date', sa.Date(), nullable=True, comment='Scheduled follow up date'),
    sa.Column('trial_start', sa.Date(), nullable=True, comment='Trial start date'),
    sa.Column('trial_end', sa.Date(), nullable=True, comment='Trial end date'),
    sa.Column('assigned_to', sa.Uuid(), nullable=True, comment='Staff member assigned to manage this lead'),
    sa.Column('converted_member_id', sa.Uuid(), nullable=True, comment='Reference to member ID if converted'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_leads_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['converted_member_id'], ['members.id'], name=op.f('fk_leads_converted_member_id_members'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    comment='Walk-in and prospective member tracking'
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_follow_up_date'), ['follow_up_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_phone'), ['phone'], unique=False)

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Monthly salary for staff members (null for regular members)'))
        batch_op.add_column(sa.Column('shift', sa.String(length=50), nullable=True, comment='Work shift for receptionists: morning/evening/full-day'))
        batch_op.add_column(sa.Column('joining_staff_date', sa.Date(), nullable=True, comment='Staff employment start date (separate from member joining_date)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('joining_staff_date')
        batch_op.drop_column('shift')
        batch_op.drop_column('salary')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_phone'))
        batch_op.drop_index(batch_op.f('ix_leads_id'))
        batch_op.drop_index(batch_op.f('ix_leads_follow_up_date'))

    op.drop_table('leads')
    # ### end Alembic commands ###
