"""add_password_reset_tokens_receipts_counter_receipt_number

Revision ID: 432277b6125a
Revises: c3634d191b2f
Create Date: 2026-07-04 17:30:43.923106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '432277b6125a'
down_revision: Union[str, Sequence[str], None] = 'c3634d191b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts_counter',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipts_counter')),
    comment='Stores sequence counters for payment receipt generation'
    )
    with op.batch_alter_table('receipts_counter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_counter_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_counter_year'), ['year'], unique=True)

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=255), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Foreign key referencing the User requesting the reset',
               existing_nullable=False)
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               comment=None,
               existing_comment='Cryptographically secure random hex reset token',
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp after which the reset token is invalid',
               existing_nullable=False)
        batch_op.alter_column('is_used',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Flag indicating if the reset token has already been consumed',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Creation time of the password reset token',
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_created_at'), ['created_at'], unique=False)
        batch_op.create_table_comment(
        'Stores password reset tokens with audit trail',
        existing_comment='Stores secure verification tokens used to recover user accounts'
    )

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_number', sa.String(length=20), nullable=True, comment='Sequential receipt number e.g. PRRO-2026-000001'))
        batch_op.create_index(batch_op.f('ix_payments_receipt_number'), ['receipt_number'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_password_changed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the user last changed their password'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_password_changed_at')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_receipt_number'))
        batch_op.drop_column('receipt_number')

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Stores secure verification tokens used to recover user accounts',
        existing_comment='Stores password reset tokens with audit trail'
    )
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_created_at'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Creation time of the password reset token',
               existing_nullable=False)
        batch_op.alter_column('is_used',
               existing_type=sa.BOOLEAN(),
               comment='Flag indicating if the reset token has already been consumed',
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp after which the reset token is invalid',
               existing_nullable=False)
        batch_op.alter_column('token',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               comment='Cryptographically secure random hex reset token',
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               comment='Foreign key referencing the User requesting the reset',
               existing_nullable=False)
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('used_at')

    with op.batch_alter_table('receipts_counter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipts_counter_year'))
        batch_op.drop_index(batch_op.f('ix_receipts_counter_id'))

    op.drop_table('receipts_counter')
    # ### end Alembic commands ###
