"""add_trainer_fields

Revision ID: 65ce71ce74ad
Revises: eb5f449e1538
Create Date: 2026-07-06 20:56:59.973311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ce71ce74ad'
down_revision: Union[str, Sequence[str], None] = 'eb5f449e1538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('occupation',
               existing_type=sa.VARCHAR(length=255),
               comment='Occupation or profession of the member',
               existing_nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Height of the member in cm',
               existing_nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Weight of the member in kg',
               existing_nullable=True)
        batch_op.alter_column('medical_notes',
               existing_type=sa.TEXT(),
               comment='Medical conditions or health notes',
               existing_nullable=True)
        batch_op.alter_column('emergency_relation',
               existing_type=sa.VARCHAR(length=100),
               comment='Relationship of the emergency contact to the member',
               existing_nullable=True)

    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.String(length=50), nullable=True, comment='Unique employee identifier'))
        batch_op.add_column(sa.Column('specializations', sa.JSON(), nullable=True, comment='Multi-select list of specialization areas'))
        batch_op.add_column(sa.Column('qualification', sa.String(length=255), nullable=True, comment='Professional qualifications'))
        batch_op.add_column(sa.Column('employment_type', sa.String(length=50), nullable=True, comment='Full Time, Part Time, or Contract'))
        batch_op.add_column(sa.Column('salary_type', sa.String(length=50), nullable=True, comment='Monthly or Hourly'))
        batch_op.add_column(sa.Column('max_members', sa.Integer(), nullable=True, comment='Maximum members allowed'))
        batch_op.add_column(sa.Column('working_days', sa.JSON(), nullable=True, comment='Working days list'))
        batch_op.add_column(sa.Column('working_hours', sa.String(length=100), nullable=True, comment='Shift working hours'))
        batch_op.create_index(batch_op.f('ix_trainers_employee_id'), ['employee_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trainers_employee_id'))
        batch_op.drop_column('working_hours')
        batch_op.drop_column('working_days')
        batch_op.drop_column('max_members')
        batch_op.drop_column('salary_type')
        batch_op.drop_column('employment_type')
        batch_op.drop_column('qualification')
        batch_op.drop_column('specializations')
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.alter_column('emergency_relation',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Relationship of the emergency contact to the member',
               existing_nullable=True)
        batch_op.alter_column('medical_notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Medical conditions or health notes',
               existing_nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Weight of the member in kg',
               existing_nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Height of the member in cm',
               existing_nullable=True)
        batch_op.alter_column('occupation',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Occupation or profession of the member',
               existing_nullable=True)

    # ### end Alembic commands ###
