"""add_notifications_table

Revision ID: 94f6d9000e8b
Revises: a26227d2f9d1
Create Date: 2026-07-03 01:21:36.334095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f6d9000e8b'
down_revision: Union[str, Sequence[str], None] = 'a26227d2f9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('recipient_user_id', sa.Uuid(), nullable=False, comment='Foreign key referencing the recipient User'),
    sa.Column('type', sa.Enum('MEMBERSHIP_EXPIRING', 'MEMBERSHIP_EXPIRED', 'PAYMENT_RECEIVED', 'UNMATCHED_SCAN', 'PLAN_ASSIGNED', 'GENERAL', name='notificationtype'), nullable=False, comment='Type categorization of notification triggers'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Short summary title of the alert'),
    sa.Column('message', sa.Text(), nullable=False, comment='Full notification detail description'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='Boolean read indicator flag'),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when user marked notification as read'),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True, comment='Dynamic reference type (e.g. membership, payment, unmatched_scan)'),
    sa.Column('related_entity_id', sa.Uuid(), nullable=True, comment='Dynamic primary key reference value'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Creation time of the notification'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_notifications_recipient_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    comment='Stores inside-app notification alerts and delivery receipts'
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_user_id'), ['recipient_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
