"""initial_schema_all_models

Revision ID: a26227d2f9d1
Revises: 
Create Date: 2026-07-03 00:51:40.147252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a26227d2f9d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_plans',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Unique identifier name of the membership plan (e.g. Basic Monthly)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of what the plan includes'),
    sa.Column('duration_days', sa.Integer(), nullable=False, comment='Duration of the membership plan in days'),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Cost of the membership plan in the specified currency'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='Currency ISO code (default INR)'),
    sa.Column('features', sa.JSON(), nullable=True, comment='JSON list of feature strings describing what features this plan unlocks'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Flag indicating if the plan is available for new subscriptions'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='Order of appearance of the plan in listing pages'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_membership_plans')),
    sa.UniqueConstraint('name', name=op.f('uq_membership_plans_name')),
    comment='Stores gym membership plan configurations and pricing metrics'
    )
    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membership_plans_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='Primary login email address, unique across all users'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Securely hashed password string (Bcrypt)'),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'RECEPTIONIST', 'TRAINER', 'MEMBER', name='userrole'), nullable=False, comment='System role defining permission scopes (admin, receptionist, trainer, member)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Flag indicating if the user account is active'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment="Timestamp of the user's last successful login"),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    comment='Stores user credentials, activation status, and role definitions'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Foreign key referencing the associated user account'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='Legal full name of the user'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Primary contact phone number'),
    sa.Column('avatar_url', sa.String(length=512), nullable=True, comment='URL pointing to profile image file in storage'),
    sa.Column('date_of_birth', sa.Date(), nullable=True, comment='Date of birth of the user'),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True, comment='Gender classification (male, female, other)'),
    sa.Column('address', sa.Text(), nullable=True, comment='Residential address of the user'),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True, comment='Full name of emergency contact person'),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True, comment='Phone number of emergency contact person'),
    sa.Column('biometric_device_id', sa.Integer(), nullable=True, comment='eSSL Biometric PIN mapping users to attendance device scans'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_profiles_user_id')),
    comment='Stores personal profile and demographic details linked to user credentials'
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_biometric_device_id'), ['biometric_device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_phone'), ['phone'], unique=False)

    op.create_table('members',
    sa.Column('profile_id', sa.Uuid(), nullable=False, comment='Foreign key referencing the associated personal profile'),
    sa.Column('joining_date', sa.Date(), nullable=False, comment='Date when the member officially joined the gym'),
    sa.Column('notes', sa.Text(), nullable=True, comment='General admin or receptionist notes about the member'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_members_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_members')),
    sa.UniqueConstraint('profile_id', name=op.f('uq_members_profile_id')),
    comment='Stores gym member records linked to user profiles'
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_id'), ['id'], unique=False)

    op.create_table('trainers',
    sa.Column('profile_id', sa.Uuid(), nullable=False, comment='Foreign key referencing the associated personal profile'),
    sa.Column('specialization', sa.String(length=255), nullable=True, comment="Trainer's specialization area (e.g. Strength, Yoga, Cardio)"),
    sa.Column('experience_years', sa.Integer(), nullable=True, comment='Number of years of professional fitness training experience'),
    sa.Column('certifications', sa.JSON(), nullable=True, comment='JSON list of certification names/credentials held by the trainer'),
    sa.Column('bio', sa.Text(), nullable=True, comment='Short biography or personal description of the trainer'),
    sa.Column('is_available', sa.Boolean(), nullable=False, comment='Flag indicating if the trainer is currently accepting new members'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_trainers_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainers')),
    sa.UniqueConstraint('profile_id', name=op.f('uq_trainers_profile_id')),
    comment='Stores gym trainer details linked to user profiles'
    )
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trainers_id'), ['id'], unique=False)

    op.create_table('attendance_logs',
    sa.Column('member_id', sa.Uuid(), nullable=False, comment='Foreign key referencing the member who clocked in/out'),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=False, comment='Timestamp of check-in'),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of check-out'),
    sa.Column('source', sa.Enum('BIOMETRIC', 'MANUAL', 'QR', 'FACE_RECOGNITION', name='attendancesource'), nullable=False, comment='Source of attendance record (biometric, manual, qr, etc.)'),
    sa.Column('device_serial', sa.String(length=100), nullable=True, comment='Serial number of the biometric terminal device'),
    sa.Column('raw_pin', sa.Integer(), nullable=True, comment='Numeric biometric enrolled user ID (pin) mapped from eSSL'),
    sa.Column('marked_by', sa.Uuid(), nullable=True, comment='Foreign key referencing the staff user who recorded the entry manually'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes on check-in or manual corrections'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], name=op.f('fk_attendance_logs_marked_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_attendance_logs_member_id_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_logs')),
    comment='Stores valid check-in and check-out entries for gym members'
    )
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_logs_check_in'), ['check_in'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_logs_member_id'), ['member_id'], unique=False)

    op.create_table('diet_plans',
    sa.Column('member_id', sa.Uuid(), nullable=False, comment='Foreign key referencing the member undergoing diet management'),
    sa.Column('trainer_id', sa.Uuid(), nullable=True, comment='Foreign key referencing the trainer prescribing the nutrition'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Heading title of the diet program'),
    sa.Column('description', sa.Text(), nullable=True, comment='Explanatory description of diet targets'),
    sa.Column('daily_calories', sa.Integer(), nullable=True, comment='Target overall daily calories'),
    sa.Column('protein_grams', sa.Integer(), nullable=True, comment='Target daily protein intake in grams'),
    sa.Column('carbs_grams', sa.Integer(), nullable=True, comment='Target daily carbohydrates intake in grams'),
    sa.Column('fat_grams', sa.Integer(), nullable=True, comment='Target daily fat intake in grams'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Beginning date of the diet plan'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='Ending date of the diet plan'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Flag indicating if this diet plan is active'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_diet_plans_member_id_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('fk_diet_plans_trainer_id_trainers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diet_plans')),
    comment='Stores overall diet plans prescribed to members by trainers'
    )
    with op.batch_alter_table('diet_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diet_plans_id'), ['id'], unique=False)

    op.create_table('memberships',
    sa.Column('member_id', sa.Uuid(), nullable=False, comment='Foreign key referencing the associated member'),
    sa.Column('plan_id', sa.Uuid(), nullable=False, comment='Foreign key referencing the associated plan template'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Official start date of the subscription'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='Official expiration date of the subscription'),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'PAUSED', 'PENDING', 'CANCELLED', name='subscriptionstatus'), nullable=False, comment='Status of subscription (active, expired, paused, pending, cancelled)'),
    sa.Column('auto_renew', sa.Boolean(), nullable=False, comment='Flag indicating if membership automatically renews upon expiration'),
    sa.Column('discount_percent', sa.DECIMAL(precision=5, scale=2), nullable=False, comment='Discount percentage applied to the membership'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional comments or context about the membership'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_memberships_member_id_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['membership_plans.id'], name=op.f('fk_memberships_plan_id_membership_plans'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    comment='Stores active and historical member subscriptions to gym plans'
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_id'), ['id'], unique=False)

    op.create_table('trainer_members',
    sa.Column('trainer_id', sa.Uuid(), nullable=False, comment='Foreign key referencing the trainer id'),
    sa.Column('member_id', sa.Uuid(), nullable=False, comment='Foreign key referencing the member id'),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the trainer was assigned to the member'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Status flag indicating if the trainer assignment is currently active'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_trainer_members_member_id_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('fk_trainer_members_trainer_id_trainers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trainer_id', 'member_id', name=op.f('pk_trainer_members')),
    comment='Association table linking trainers to their assigned members'
    )
    op.create_table('unmatched_scans',
    sa.Column('device_serial', sa.String(length=100), nullable=False, comment='Serial number of the biometric terminal device'),
    sa.Column('raw_pin', sa.Integer(), nullable=False, comment='Biometric device enrolled user ID (pin) pushed from eSSL'),
    sa.Column('scan_datetime', sa.DateTime(timezone=True), nullable=False, comment='Date and time when the user finger scanned'),
    sa.Column('verified', sa.Boolean(), nullable=False, comment='Device verification status flag (1 matched, 0 unmatched)'),
    sa.Column('raw_payload', sa.JSON(), nullable=False, comment='Complete JSON structure of HTTP query parameters from the device'),
    sa.Column('is_resolved', sa.Boolean(), nullable=False, comment='Flag indicating if the receptionist resolved this scan link'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the scan was linked'),
    sa.Column('resolved_by', sa.Uuid(), nullable=True, comment='Foreign key referencing the staff user who resolved the link'),
    sa.Column('resolved_member_id', sa.Uuid(), nullable=True, comment='Foreign key referencing the member linked during resolution'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_unmatched_scans_resolved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_member_id'], ['members.id'], name=op.f('fk_unmatched_scans_resolved_member_id_members'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unmatched_scans')),
    comment='Stores biometric scanner records that failed to map to a member profile PIN'
    )
    with op.batch_alter_table('unmatched_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unmatched_scans_device_serial'), ['device_serial'], unique=False)
        batch_op.create_index(batch_op.f('ix_unmatched_scans_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unmatched_scans_raw_pin'), ['raw_pin'], unique=False)

    op.create_table('workout_plans',
    sa.Column('member_id', sa.Uuid(), nullable=False, comment='Foreign key referencing the member undergoing training'),
    sa.Column('trainer_id', sa.Uuid(), nullable=True, comment='Foreign key referencing the trainer prescribing the plan'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Heading title of the workout program'),
    sa.Column('description', sa.Text(), nullable=True, comment='Explanatory description of plan focus or remarks'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Beginning date of the workout plan'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='Ending date of the workout plan'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Flag indicating if this workout program is active'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_workout_plans_member_id_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('fk_workout_plans_trainer_id_trainers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_plans')),
    comment='Stores overall workout plans prescribed to members by trainers'
    )
    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_plans_id'), ['id'], unique=False)

    op.create_table('diet_items',
    sa.Column('plan_id', sa.Uuid(), nullable=False, comment='Foreign key referencing the associated diet plan'),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', 'PRE_WORKOUT', 'POST_WORKOUT', name='mealtype'), nullable=False, comment='Meal type categorization (breakfast, lunch, snack, etc.)'),
    sa.Column('food_name', sa.String(length=255), nullable=False, comment='Name of the food item (e.g. Oats, Egg Whites, Chicken Breast)'),
    sa.Column('quantity', sa.String(length=100), nullable=False, comment='Portion quantity (e.g. 100, 2, 1.5)'),
    sa.Column('unit', sa.String(length=50), nullable=False, comment='Portion measurement unit (e.g. grams, ml, pieces)'),
    sa.Column('calories', sa.Integer(), nullable=True, comment='Calculated calorie count of this food portion'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Preparation or eating instructions'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='Sequence index order of the food item in the meal'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['diet_plans.id'], name=op.f('fk_diet_items_plan_id_diet_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diet_items')),
    comment='Stores specific food items, caloric values, and portions linked to diet plans'
    )
    with op.batch_alter_table('diet_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diet_items_id'), ['id'], unique=False)

    op.create_table('payments',
    sa.Column('membership_id', sa.Uuid(), nullable=False, comment='Foreign key referencing the associated membership purchase'),
    sa.Column('member_id', sa.Uuid(), nullable=False, comment='Denormalized foreign key referencing the associated member for speed'),
    sa.Column('amount_paid', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='Total monetary value paid'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='Currency ISO code (default INR)'),
    sa.Column('payment_method', sa.Enum('CASH', 'UPI', 'CARD', 'BANK_TRANSFER', 'OTHER', name='paymentmethod'), nullable=False, comment='Method of payment (cash, upi, card, bank_transfer, other)'),
    sa.Column('payment_status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False, comment='Status of the transaction (pending, completed, failed, refunded)'),
    sa.Column('transaction_reference', sa.String(length=255), nullable=True, comment='Bank or payment gateway reference ID (e.g. UPI Ref, Card Tx ID)'),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the payment occurred'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Receptionist comments about the invoice/payment'),
    sa.Column('collected_by', sa.Uuid(), nullable=True, comment='Foreign key referencing the staff user who collected the payment'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], name=op.f('fk_payments_collected_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_payments_member_id_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_payments_membership_id_memberships'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    comment='Stores individual payment transaction logs and methods'
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_transaction_reference'), ['transaction_reference'], unique=False)

    op.create_table('workout_exercises',
    sa.Column('plan_id', sa.Uuid(), nullable=False, comment='Foreign key referencing the associated workout plan'),
    sa.Column('day_of_week', sa.Integer(), nullable=False, comment='ISO day index (1 = Monday, 7 = Sunday) when this exercise occurs'),
    sa.Column('exercise_name', sa.String(length=255), nullable=False, comment='Name of the exercise (e.g. Squat, Bench Press)'),
    sa.Column('sets', sa.Integer(), nullable=True, comment='Prescribed sets quantity'),
    sa.Column('reps', sa.Integer(), nullable=True, comment='Prescribed reps per set'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='Duration in minutes (for cardio/endurance)'),
    sa.Column('rest_seconds', sa.Integer(), nullable=True, comment='Rest time in seconds between sets'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Pacing or equipment instructions'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='Sequence index order of the exercise in the plan'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], name=op.f('fk_workout_exercises_plan_id_workout_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_exercises')),
    comment='Stores exercise items, sets, reps, and pacing linked to workout plans'
    )
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_exercises_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_exercises_id'))

    op.drop_table('workout_exercises')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_transaction_reference'))
        batch_op.drop_index(batch_op.f('ix_payments_id'))

    op.drop_table('payments')
    with op.batch_alter_table('diet_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diet_items_id'))

    op.drop_table('diet_items')
    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_plans_id'))

    op.drop_table('workout_plans')
    with op.batch_alter_table('unmatched_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unmatched_scans_raw_pin'))
        batch_op.drop_index(batch_op.f('ix_unmatched_scans_id'))
        batch_op.drop_index(batch_op.f('ix_unmatched_scans_device_serial'))

    op.drop_table('unmatched_scans')
    op.drop_table('trainer_members')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('diet_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diet_plans_id'))

    op.drop_table('diet_plans')
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_logs_member_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_logs_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_logs_check_in'))

    op.drop_table('attendance_logs')
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trainers_id'))

    op.drop_table('trainers')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_id'))

    op.drop_table('members')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_phone'))
        batch_op.drop_index(batch_op.f('ix_profiles_id'))
        batch_op.drop_index(batch_op.f('ix_profiles_biometric_device_id'))

    op.drop_table('profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membership_plans_id'))

    op.drop_table('membership_plans')
    # ### end Alembic commands ###
