"""add_password_reset_tokens

Revision ID: c3634d191b2f
Revises: 94f6d9000e8b
Create Date: 2026-07-04 17:20:45.323696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3634d191b2f'
down_revision: Union[str, Sequence[str], None] = '94f6d9000e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Foreign key referencing the User requesting the reset'),
    sa.Column('token', sa.String(length=255), nullable=False, comment='Cryptographically secure random hex reset token'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp after which the reset token is invalid'),
    sa.Column('is_used', sa.Boolean(), nullable=False, comment='Flag indicating if the reset token has already been consumed'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Creation time of the password reset token'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    comment='Stores secure verification tokens used to recover user accounts'
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_expires_at'))

    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
