"""add_exercise_library_and_gym_settings

Revision ID: eb5f449e1538
Revises: 4173fc7fe402
Create Date: 2026-07-05 14:15:36.458905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb5f449e1538'
down_revision: Union[str, Sequence[str], None] = '4173fc7fe402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_library',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Unique name of the exercise'),
    sa.Column('muscle_group', sa.Enum('CHEST', 'BACK', 'SHOULDERS', 'BICEPS', 'TRICEPS', 'LEGS', 'GLUTES', 'CORE', 'CARDIO', 'FULL_BODY', name='musclegroup'), nullable=False, comment='Primary target muscle group'),
    sa.Column('equipment', sa.String(length=100), nullable=True, comment='Required training equipment (e.g. Barbell, Dumbbell)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Short explanation or video URL instructions'),
    sa.Column('default_sets', sa.Integer(), nullable=True, comment='Default recommended sets count'),
    sa.Column('default_reps', sa.Integer(), nullable=True, comment='Default recommended repetitions count'),
    sa.Column('default_rest_seconds', sa.Integer(), nullable=True, comment='Default recommended rest period in seconds'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_library')),
    comment='Stores standard workout exercises catalog for trainers to pick from'
    )
    with op.batch_alter_table('exercise_library', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_library_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_library_name'), ['name'], unique=True)

    op.create_table('gym_settings',
    sa.Column('key', sa.String(length=100), nullable=False, comment='Settings parameter key lookup identifier'),
    sa.Column('value', sa.Text(), nullable=True, comment='Configured string value payload'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Settings categorization grouping (general, finance, notifications, hours)'),
    sa.Column('label', sa.String(length=255), nullable=False, comment='Human readable descriptive title'),
    sa.Column('description', sa.Text(), nullable=True, comment='Help text explanation of setting parameter use'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gym_settings')),
    comment='Stores gym operating configuration parameters (e.g. Opening times, GST %, currencies)'
    )
    with op.batch_alter_table('gym_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gym_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gym_settings_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gym_settings_key'))
        batch_op.drop_index(batch_op.f('ix_gym_settings_id'))

    op.drop_table('gym_settings')
    with op.batch_alter_table('exercise_library', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_library_name'))
        batch_op.drop_index(batch_op.f('ix_exercise_library_id'))

    op.drop_table('exercise_library')
    # ### end Alembic commands ###
